#/bin/bash

INPUT_DIR="/ESPRESSO_NLP/input"
OUTPUT_DIR="/ESPRESSO_NLP/output/raw"
OUTPUT_SUMMARY_DIR="/ESPRESSO_NLP/output/summary"
RULES_DIR="/ESPRESSO_NLP/SBI"

java -Xms512M -Xmx2000M -jar MedTagger-fit-1.0.2-SNAPSHOT.jar $INPUT_DIR $OUTPUT_DIR $RULES_DIR

python SBI/model/run_output_sbi.py $OUTPUT_DIR $OUTPUT_SUMMARY_DIR "0"
